image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      cd ./startMcServer && npm install
      cd ./stopMcServer && npm install
      cd ./inviteToMcServer && npm install
#    command: './cluster-scripts/prep-project.sh'
  - command: |
      gcloud init
      gcloud auth application-default login
